app:
  name: tritter
  home: C:\${app.name}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:\tritter\db\tritter;MODE=PostgreSQL
    username: sa
    password: 
